### ISSUE TITLE
迁移 core 的部分代码

### ISSUE THREAD

**Issue by bytemain** [opensumi/di#1]
1. di-helper

**Comment by erha19** [comment]
link https://github.com/opensumi/core/issues/130

**Comment by vagusX** [comment]
just do it

**Comment by bytemain** [comment]
目前看来我心目中的部分代码似乎并不需要迁过来，#5 的迁移也不是很成功，会在 #14 中移除掉。

先关了，剩余事情在 https://github.com/opensumi/core/issues/130 中讨论。
