### ISSUE TITLE
[咨询] getFromDomain 为什么不能继承 parent 的 domainMap 呢？

### ISSUE THREAD

**Issue by miserylee** [opensumi/di#104]
RT，如果在 child injector 中绑定了 contribution provider，这个 provider 调用 getContributions 时获取不到实例，除非把 parent 的 providers 在 child 再 add 一次才行

**Comment by bytemain** [comment]
给下复现用例

**Comment by bytemain** [comment]
看了下，需求是合理的，我们没实现这个功能。
在 #108 中实现了：
- #108

**Comment by bytemain** [comment]
- https://github.com/opensumi/di/releases/tag/v1.9.0

已发布
