### ISSUE TITLE
使用disposeOne后，实例没有被销毁

### ISSUE THREAD

**Issue by hcxw11** [opensumi/di#109]
## 诉求
在B里面通过@Autowired注入A，然后对A的token执行了disposeOne，此时在B内再次使用A时，应该重新创建实例

## 复现场景
下面的例子在B里面通过@Autowired注入A，然后对A的token执行了disposeOne，，但是b.a返回的对象还是之前a的实例

```typescript
import { Injectable, Injector, Autowired } from '../../src';

@Injectable()
class A {
  num = 1;

  add() {
    this.num += 1;
  }
}

@Injectable()
class B {
  @Autowired()
  a!: A;
}

describe('dispose', () => {
  let injector: Injector;

  beforeEach(() => {
    injector = new Injector();
  });

  it('成功进行批量对象销毁', async () => {
    const a = injector.get(A);
    const b = injector.get(B);
    expect(injector.hasInstance(a)).toBeTruthy();
    expect(injector.hasInstance(b)).toBeTruthy();

    b.a.add();
    expect(b.a.num).toBe(2);

    injector.disposeOne(B);
    expect(injector.hasInstance(b)).toBeFalsy();

    // 这里的 A 的实例并没有被销毁，并且因为 Autowired 内有缓存的原因也不会再创建了
    expect(b.a.num).toBe(1); // 目前还是2
    expect(injector.hasInstance(b)).toBeTruthy(); // 目前这里是 false
  });
});
```

## 原因
https://github.com/opensumi/di/blob/e4e6bf57b8aec4f18b63be02b73ebbbac7f6608d/src/decorator.ts#L97-L110

在@Autowired的实现上取值时通过Symbol做了缓存，这个缓存是独立在di之外的，在dispose时并不会清理这个缓存，导致再次获取值的时使用的还是缓存的内容。

这个问题导致两个问题：
1. 这样如果要重新生成 A 的实例，就必须要把  B 也清理重新生成了才行，会比较奇怪，如果哪个地方忘了清理，就会出现虽然写法上预期是单例的，但是实际使用上会有多个实例
2. 这个缓存的实例会被注入的地方持续引用，内存无法释放

**Comment by bytemain** [comment]
期望的正确表现应该是，这里 disposeOne 后，B 上的 a 的引用应该也删掉才对，这个我提个 PR 修复一下吧。

**Comment by bytemain** [comment]
可以看看：
- #110

你给的 testcase 似乎是和描述不一样的，所以我自己写了一份 testcase: https://github.com/opensumi/di/pull/110/files#diff-5599ec6aa3297fcee8a4f8b70fd83cab17765fa3dfa80de2a5b99665e60ad87bR115

![CleanShot 2023-10-13 at 11 40 20@2x](https://github.com/opensumi/di/assets/13938334/fc4389a7-7552-4962-9321-f9750ece97a9)

**Comment by bytemain** [comment]
- https://github.com/opensumi/di/releases/tag/v1.9.0

已发布
