### ISSUE TITLE
DI Autowired无法工作，是否对 webpack 打包脚本有什么特别的要求

### ISSUE THREAD

**Issue by geekeren** [opensumi/di#115]
我们开发了一个 基于Opensumi 的 SDK，在自己的demo页面工作良好，但是提供给外部引用（monorepo源码引用）后，发现大量 DI 无法工作的场景。
![image](https://github.com/opensumi/di/assets/13082375/56d26614-5780-418f-a446-f3f8ea0165ec)
不知道是不是 对webpack 配置有特殊要求，已经开启了对修饰器的编译支持，打断点确定 autowired 函数已经运行。

## 下面是最小复现的 demo。

// const.ts
```typescript
export const TestToken = Symbol('token');
export const TestClassToken = Symbol('TestClassToken');
```

// TestClass.ts
```typescript
import { Injectable, Autowired } from '@opensumi/di';

import { TestToken } from './const';

@Injectable()
export class TestClass {
  @Autowired(TestToken)
  public value: string;
}
```

// index.ts

````typescript
const injector = new Injector();
injector.addProviders({
  token: TestToken,
  useValue: 'test',
});
injector.addProviders({
  token: TestClassToken,
  useClass: TestClass,
});

console.log('TestClassToken', injector, injector.get(TestClassToken), injector.get(TestClassToken).value); // 这里 value为undefined
```

**Comment by bytemain** [comment]
估计是 Webpack 打包后，每次获取的 Symbol('XXX') 都是不一样的：
![CleanShot 2023-11-09 at 11 27 58@2x](https://github.com/opensumi/di/assets/13938334/e7759e58-c033-40ff-b2c3-f4e80f0b8dc1)

**Comment by vagusX** [comment]
terser 开启不压缩 classnames 和 function names

**Comment by geekeren** [comment]
跟ts loader有关系，用 rspack 默认打包配置不行，把 ts-loader 改成 esbuild 后就可以了
