### ISSUE TITLE
1.x版本的库可以正常运行，2.x版本之后不行了

### ISSUE THREAD

**Issue by djkloop** [opensumi/di#121]
### 环境信息
![image](https://github.com/opensumi/di/assets/21050914/3c8c3e98-9786-4375-9df7-fdd893cd45e3)

### 报错图
![image](https://github.com/opensumi/di/assets/21050914/f9bfc7c5-5f9d-4610-9eb9-d32c0785b755)

### 运行正常的环境信息
![image](https://github.com/opensumi/di/assets/21050914/2a0867c5-112e-4ce6-a0c0-9b3980c17350)

**Comment by bytemain** [comment]
看起来是跟 esm 有关，我们的 2.x 版本也自带了一份 cjs 的，你看看是不是可以调一下 webpack 配置。

**Comment by djkloop** [comment]
@bytemain 

#### 我这么设置了一下可以了...
![image](https://github.com/opensumi/di/assets/21050914/e76dd8c1-ca2e-49e2-92f1-2fe88d0189ad)
