### ISSUE TITLE
在vite创建出来的项目中使用Autowired异常

### ISSUE THREAD

**Issue by lixin131** [opensumi/di#122]
在vite 5 创建的环境中使用 2.1.0版本，使用Autowired的代码截图如下

![1](https://github.com/opensumi/di/assets/63175579/56ef5788-18bc-4e31-8eb4-37cb6a413167)

但是从容器中获取SplitPanelManager实例的时候，实例属性injector为undefined，而有效值则在SplitPanelManager类的原型上。打印对象截图如下

![2](https://github.com/opensumi/di/assets/63175579/0ea4541b-2307-44ec-88a7-5b9c65e6e331)

删除实例属性Injector才能访问到注入的对象，因自身技术差找不出问题出在哪里，该怎样操作才能解决问题。

**Comment by bytemain** [comment]
感谢反馈，vite5+typescript5 复现了这个问题，我来看一下：
![CleanShot 2024-02-29 at 16 28 29@2x](https://github.com/opensumi/di/assets/13938334/15108009-bb7f-4da9-961e-2725a295be45)

**Comment by bytemain** [comment]
<img width="676" alt="image" src="https://github.com/opensumi/di/assets/13938334/15beec06-036d-4c89-b1e4-74c80e22eae2">

after some investigation, I found that turn off the `useDefineForClassFields` options can make `@opensumi/di` work.

https://vitejs.dev/guide/features.html#usedefineforclassfields

we are thinking how to avoid this problem.

---

more infos:
- https://github.com/microsoft/TypeScript/issues/48814
- https://github.com/microsoft/TypeScript/issues/35081
- https://mobx.js.org/installation.html#transpilation-settings
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

**Comment by bytemain** [comment]
we will provide a new version that support the new es decorator.

**Comment by lixin131** [comment]
非常谢谢，通过修改tsconfig.json能解决问题。
