### ISSUE TITLE
【QA】请教一下，这个类什时候能释放掉？

### ISSUE THREAD

**Issue by djkloop** [opensumi/di#123]
#### 因为我们是vue的项目，而且是嵌套在qiankun中的某个子项目，我们需要在切换到其它的子项目时需要释放掉这些类，想问下这些类什么情况下会释放掉？有没有什么手动的api可以释放这些类？主要是害怕内存泄漏相关的....

**Comment by bytemain** [comment]
可以使用 `Injector.disposeOne` 和 `Injector.disposeAll` 来释放 Token。

这两个方法会从 DI 容器中删除当前已创建的实例，并尝试调用这个实例的 `dispose` 方法（可以没有）。

**Comment by djkloop** [comment]
额...找到了test下的示例了，
https://github.com/opensumi/di/blob/main/tests/injector/dispose.test.ts
这个文档后期会完善吗？

**Comment by bytemain** [comment]
可以的，我之后补充一下文档
