### ISSUE TITLE
Bug: Contructor injection does not work

### ISSUE THREAD

**Issue by snnsnn** [opensumi/di#42]
Hi, I was going through the example, I could not reproduce injections via constructors:

```typescript
import { Inject, Injectable, Injector } from '@opensumi/di';

interface Drivable {
  drive(): void;
}

@Injectable()
class Student {
  constructor(@Inject('Drivable') public vehicle: Drivable) {}

  go() {
    this.vehicle.drive();
  }
}

@Injectable()
class Car implements Drivable {
  drive() {
    console.log('Driving Car');
  }
}

const injector = new Injector();
injector.addProviders(Student);
injector.addProviders({ token: 'Drivable', useClass: Car });

const student = injector.get(Student);
student.go();
```

This outputs:

```
Running.. [index.ts:13:12](webpack://kiki/application/src/index.ts)
Uncaught TypeError: this.vehicle is undefined
    go index.ts:14
```
Explicitly assigning the property in the constructor also did not work:

```typescript
constructor(@Inject('Drivable') public vehicle: Drivable) {
  this.vehicle = vehicle;
}
```

Then I tried the example from the README file, which also did not work:

```typescript
import { Inject, Injectable, Injector } from '@opensumi/di';

@Injectable()
class A {
  constructor() {
    console.log('Create A');
  }
}

@Injectable()
class B {
  constructor(public a: A){}
}

const injector = new Injector();
injector.addProviders(A, B);

const b = injector.get(B);
console.log(b.a instanceof A);  // false
console.log(b.a);  // undefined
```

Using a token did not change the situation, `b.a` still returns `undefined`.

**Comment by bytemain** [comment]
Please check your tsconfig.json:

you should enable these two configs:

```json
{
    "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true
    }
}

```

I'm using ts-node, the code is worked

<img width="1026" alt="CleanShot 2022-07-15 at 14 49 42@2x" src="https://user-images.githubusercontent.com/13938334/179167671-e383891e-a449-4053-a769-371bb48ad541.png">

**Comment by snnsnn** [comment]
I did use `emitDecoratorMetadata` and `experimentalDecorators`. I tried in codesandbox, it works. Probably it is because of my setup, could be Babel plugin `@babel/plugin-proposal-decorators` that I use.
