### ISSUE TITLE
What about `tsyringe` ?

### ISSUE THREAD

**Issue by AkatQuas** [opensumi/di#8]
How do you contributors like [`tsyringe`](https://github.com/microsoft/tsyringe) ?

Would you help me to find out differences between `tsyringe` and `opensumi/di`.

Thank you.

**Comment by bytemain** [comment]
Sorry for the late reply, I'm not familiar with `tsyringe`, but it seems to be a very powerful DI tool too.
[tsyringe](https://github.com/microsoft/tsyringe) has some features that @opensumi/di do not have, and its' document is more detailed.
